spring:
  data:
    mongodb:
      uri: ENC(uMQ15T05MUrjUg2ToydDW3nX0e4i7VIp4OkrhpuLxPfwnRLkpr43QNEDJiERvoDC6bp7A5PHfraJwwvrzMwlo6xCEG+wk2wzpDA3FGQbNzNRTtvocNpzpuL0jrH8GQsWP1ARnOzuNFRQGV5GYjqUhsq3MS6D4XYONZa1HerRkkA=)
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  config: classpath:logback/logback-dev.xml
  save-path: /var/log
  file-name: bookwhale-dev-chat
  error-file-name: bookwhale-dev-chat-ERROR
  slack:
    webhook:
      url: ENC(ioP3KNC/rHu1pwN7yPTJv05g8M7FQuljnIAJ1Lj1heZuJeyS24Qt7vQBJPzvAa/aWE0Ma6kaW5dqYSUgsXih1MsqUCWMPxV38N7pqMaeSjIFYSuK0IfJ3k7e8wF3gZ4J)