spring:
  datasource:
    url: jdbc:h2:mem:bookwhale
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  config: classpath:logback/logback-local.xml
external-api:
  auth:
    naver:
      callback-url: http://localhost:8080/api/oauth/naver/issueToken
    google:
      callback-url: http://localhost:8080/api/oauth/google/issueToken
