# S3 image bucket
cloud:
  aws:
    s3:
      bucket: ENC(NbvLFTfTrn7rstFlukvjkBoXBcNomHXf)
    region:
      static: ap-northeast-2
    credentials:
      access-key: ENC(BWi7T33mSYbxlkutVpsVxWcedUqjbB62BPsQhRbt7SU=)
      secret-key: ENC(7JgiB7WHHW/BeWqI8aDgIKUz7dwl3Ns1V/3ZbzeEA8fZ6MXoihBlw4Dh9Rz9TL42Lvpl1YPYTfA=)
      instance-profile: true
    stack:
      auto: false
# OAuth, Token
external-api:
  auth:
    naver:
      client-id: ENC(Tznm/ok9QEJ6iJU8i07QU9cjVDVFBHpX59c0ztp5fMI=)
      client-key: ENC(nGQtzCp7nQFf+RfRkpZ4KvtIMo2plbCd)
      base-url: https://nid.naver.com/oauth2.0/authorize
      state: whale
      callback-url: http://localhost:8080/api/oauth/naver/issueToken
      access-token-url: https://nid.naver.com/oauth2.0/token
    google:
      client-id: ENC(ky7Fs/NURcBOuo7ncPOWrIe0m6ifM0c4QTdnQxwysRSV/8M05qMUbXklav+TauYGmfMVKU7DrFuXo19gWit6yqYvEjZHXahVbSJk6rjAOyCL7fiqTIW8ig==)
      client-key: ENC(afk3fc9o+Nj7mUZZe6OWI9A6IEkHNw28reztrSke9/cggJKgffehT314mJlMk5bm)
      base-url: https://accounts.google.com/o/oauth2
      callback-url: http://localhost:8080/api/oauth/google/issueToken
      access-token-url: https://oauth2.googleapis.com/token
    kakao:
      client-id: ENC(x/JMCEbTBpKQz1KjHFp7DtECwtQBzfk/+4ZDIIWw67cLI7N3eK9Crx89xtJ28nvg)
      client-key: ENC(c2JDQafDFQE8hHg/zq5vv46w7pJ46O4diXoGeiERgc5mec3l3elulc7kWcEt/Dyw)
      base-url: https://kauth.kakao.com/oauth
      state: whale
      callback-url: http://localhost:8080/api/oauth/kakao/issueToken
      access-token-url: https://kauth.kakao.com/oauth/token
  firebase:
    access-token: ENC(+joehjj4LSKDus+lW30D8dEqYDjHu4aqG6AXnqPPkd392JN5hwb7OLR0KSmnq0Ly2NOkdrW10ErvvpR6qPhN77VSk71WopUbsXSqhGVCtnCjQFejkG19LcDHS/M/8QBcW1bX7H/L6UM9/mhQsoub7c2xxU6OYJLwN3B92vHSdt5n13Lmuah8AN6pxvhzny7CUFOruipLtil6U4fLvyJF3MTXBO084GeLEl3yfmsPS/EDJG2lm9Dw5D6nLdFVANkxGAB/amsCvO5Kvfa/uWWS2CIp5d0oHfN5xvPaGFeERMbsUIFLm8heNz156/Miv8iorUMdxLYj690rEpSe0q7fqBsvy69tkRYY2W6R2HntZmsTpUqjITfhkq5MqkfbY+0llqlPKpJZwqzsxFfAPZ+F3e9o/h/Z+UkYAQhXtTw48EaE5lYZ6IUDUzbuqojremUoB+aw1G9WpVCLUcxvZivEjaBWa3oQtoBzSvuRfqHsDuycLPt53DnCeOki59X528p+IbFVjDOatz/2aZSi0j2S1zBmE3VaZrusIsCQs9wmUNhj7zkUKNXRjBSn3tQT+C1+Hbd5FhZ/qts4gLTHB9dC8LoRMwsBiwUTITvZeRf8pc3AU8oK9dslh7YZtxo3CVS7O68GDpKyDYTd3iHIDV2qMgPIFgCvJ2RBqq+BmsgmmuwuTGn00405JPsOfkmbeMqKvDkKyalkDYKw1p1Fo7RQ2QfY3c/NdPnQDA7bZIQcIX5aNeM5w0flsYvfwab20Mg307Ydpy2Z8Ic+kpfy78akjSqmi4McqQfxRwWTQaduwfmO8CAcPr9JkCk7E8ivxJx52I71axb1k0anFlvVUENOfXsr+AwcnPxn9Ilkt/dbwKqaz2dmedxMXCGh3uMmH/Uov7QW6VsqAITXgqVXMzTeW8o/ZclrKwgkNBHUtDMdhAbq+bFpbb/x3jrKD/tv2R0LYXAoThO41od39ncqL7B81/Jl9Z5f/LJwBtq+FTaqa8u6i8p1amSX+fjeSWpBD2+b8fTBcli5S4lIPnccTbz/KRJokysMt5SQQj+WfFZffadJC7mk2BLGMiVbBGxhyu2TnDjHfZmQ5hVC5r3Ri0jCDwHDeIQFT3MaoQcDx1xPeg+QapYQy9JYQnzQwkpivIFEFuJoobSIKi86nrTCQVo/UyFmJ4WcGt8dZ7L+Qa1oRYvWcb5Rx/rXKldkBcuEkYH4bnXZ2Lhe2cK7BNx5qTbMZDjLpfrK4C2Kfv6HBxXa2/59IpSrC8gMKEIO7DmLEXpbnM6pRqr+WIVK4guinrXenvbfdzrqRou3R4dktH/NZByq3VYDsU6Ecgbwn0i7AtCtLNNNURaCRjBUGddCgh37frd2lXrvvmBibpkhTw6mqDeO/BG9ELvGcj7qhvLdNNrhrAzfZSk/nix176o6SCiHhTyfI0ryhLAUFdFcPxDsFKa1oK8MK0g7GZL9k2jrzHshUFj+BpHGaXSitBi3XiljEj32TfmikzHXs3HYKPVay2xhco43wVyLiMi6RduJRiJSdQ23hN7cxgadql9lBu/I+rp5aZs2m5rAI7Pn4BrigERNvpkeC2oyxQy2wxYMaxujUVFjuGV+uUbg40/9HH5B4UKoh4dL1ibWLBcAZ0D3x1sahu/qCcVfGbsQaKl3z0kUgowlgdzkICz/rsBSdBjb1dwLAoGEyrKXBlolvVCxG1nFCo1h4ofsN0MLFCQL8+xhDt5JtoBmnPCqxA23W+7eFRrZVpSPll3En5fjhWB0iaZxt22HF4hWC1BOIA1wsgcg+2oAcsh+PN3ercG7CMWzgcekSU5zC5QRs/6EwKdabgUM0DKfZ4Gtf5f/arFzCrhT9+JSRF+sJ7y0EqVZJOv+KmVwUXJRMzSZx31Dg6/2bs+mcZb1MutUoE4pQWcfN5WlWsU743Fq0JNSYWFx1uAdM932UtyrDk5HG8576Ay4Vy4eLcpdZDmEgVezroJjWerLtkNrbgt7X/b6RVkpI83hMmb61tGfYgGs1dqTeH21V5X0gzsv9MRWa2VCPPH48cG4XcJPVzRFrfbm+J/t/Ur9dCXlhEHNZJS3Zrg5lMBOKcbD0kLxjrF9kaKXhlo0zI1tcpBES0wgt8yTyU1MUv7K/J40LQF4oitcHEfPS1qcj0wsqEV236+kaIeM2WQmCvIm//NON6aFOGFwf9giWLRxyeh5LGspWvdSR0LkWU25oceuqNfmoiqH72rfFExSBk3a8Cr1QCZYh1WXK/YSOeJKJuxO6tBLgvbdoSb0Y3bKz3UPGW5cptkYPNP2xi6VlktgpCxWHYQQxMR2AusgPukdLfxnTFdwfKWHfFoJ6KjbnmM1stXNvH/Hl3Sf3NVEJZueOsCOExPBsZxxMkfpfOGQN8CSoy/fILGcmL1SFpz6UyHGLgNRbRtwNMVT9IIqER4vvYqcZ5NIcoPlQEp463Wc/JiwhgSTU1YUrZLyYz76i0itOCYzocnQHrjoRxYrygHIDXQurRCuCkT5ILr22Ra1k3ZXaln1RNj0uCVnQqgD+TKrUE1ua0ZM+o7TIlXydZhwQb0m3XK4c6mERkskgjIKygUlF12IOoNYK/OYKV2tB+vIlxclj++49n6YJc6x1+1QDgw6vX1BUcOF2/qDCtf3qxRjInnS3T2zxtq2klO40DO5uu82FvTImsdTQl+zkWYA6AMYoWIpNTZyscutKr8ypZw2+G62tXerX090UB0aZeyvgBC6JZ+ax/lgdg33o2oBgeQWjl1Cm3vRmiJdGdTgcPztWvrvJIpsmaqjIMtWf5bq1pZGwA5vDrgn0UPqH1ewjSHdx6cpfN7/R3ftznKjNw8KD5KjBmShMBptxTAEm9a+IgsGa9/dCz2TVwOpnayLA6pKT/JjX8UnaKMWp8JUE7nphv7DZrfi40P1TxmWoApCN9ZuWAr4n56GEdtwWry6Th0PuvcnamALNbIim1FmYjMuGd0ZpFlf7w0kp7w6otjKvWiJDxfA2z+FeQ3mgH03k2QHBC+J4dKGdfDs3V2o/mZAYQ5LC1FlI21hIUXKIwzWqi25bWTfTs2hjzdA+YHtGXZ1KqHQjFyGGZRV8iNEzlADO2u1MgrEFekbrC8YSf7jJ3RSm26LDOAMywHmdIK8rth3Li/aq38=)
jwt:
  token:
    header: api_key
    issuer: bookwhale_server
    clientSecret: ENC(alIW2awsA5PjqVkn+DpVJI3P+9/Vxyfw)
    expirySecond: 1800
    expiryRefreshSecond: 604800
