name: Backend Develop Deploy

on:
  push:
    branches: [ develop-renewal ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 브랜치 체크아웃
      uses: actions/checkout@v2
    
    - name: JDK 11 버전 설정
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: API 서버 gradlew 권한 수정
      run: chmod +x gradlew
      
    - name: API 서버 빌드 진행
      env:
        BOOKWHALE_JASYPT_PASSWORD: ${{ secrets.JASYPT_PASSWORD }}
      run: ./gradlew clean build
      
    - name: API 서버 jar 파일 복사
      run: cp ./api/build/libs/api-1.0.jar ./deploy/api

    - name: CHAT 서버 jar 파일 복사
      run: cp ./chat/build/libs/chat-1.0.jar ./deploy/api
      
    - name: AWS EC2에 Repository 복사
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: '.'
        target: '/home/ubuntu/app/bookwhale-server'
      
    - name: AWS EC2에 접속 후 API 서버 배포 스크립트 실행
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/app/bookwhale-server/deploy/api
          sudo chmod 666 /var/run/docker.sock
          sudo docker stop bookwhale-server
          sudo docker rm bookwhale-server
          sudo docker rmi bookwhale-server
          sudo docker build -t bookwhale-server:latest .
          sudo docker run -d -v /tmp/log:/var/log -p 8080:8080 -p 9090:9090 --name bookwhale-server -e BOOKWHALE_JASYPT_PASSWORD=${{ secrets.JASYPT_PASSWORD }} bookwhale-server:latest
